branch-defaults:
  master:
    environment: doc-to-pdf-dev
    group_suffix: null
global:
  application_name: doc-to-pdf
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  #profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
